OK_FORMAT = True

test = {   'name': 'q1-4',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': ">>> assert 'chicken_material' in globals(), 'chicken_materialが定義されていません'\n>>> assert chicken_material == 60, 'chicken_materialの値が正しくありません'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert 'chicken_purchased' in globals(), 'chicken_purchasedが定義されていません'\n>>> assert chicken_purchased == 5000, 'chicken_purchasedの値が正しくありません'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert 'cost_of_chicken' in globals(), 'cost_of_chickenが定義されていません'\n>>> assert cost_of_chicken == 3400.0, 'cost_of_chickenの計算が正しくありません'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert 'number_of_dish' in globals(), 'number_of_dishが定義されていません'\n>>> assert number_of_dish == 83, 'number_of_dishの計算が正しくありません'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert 'total_sales' in globals(), 'total_salesが定義されていません'\n>>> assert total_sales == 10790, 'total_salesの計算が正しくありません'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> assert 'revenue' in globals(), 'revenueが定義されていません'\n>>> assert revenue == 7390.0, 'revenueの計算が正しくありません'\n", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
